language: java

jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
- provider: s3
  region: eu-west-1
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: de.jh.projectplanner-bucket
  local_dir: dpl_cd_upload
  skip_cleanup: false
  on:
    all_branches: true
- provider: codedeploy
  region: eu-west-1
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: de.jh.projectplanner-bucket
  key: latest.zip
  application: de.jh.projectplanner
  deployment_group: de.jh.projectplanner
  on:
    all_branches: true

script:
  - mv build/libs/*jar app.jar
  - zip -r latest app.jar appspec.yml
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload